batch_size: 4
bilinear: false
device: !!python/name:torch.device ''
input_size: !!python/tuple
- 256
- 256
learning_rate: 0.0001
model_checkpoint: experiment1\nucleus_unet.pth
n_classes: 1
num_channels: 3
num_epochs: 2
output_dir: experiment1
patience: 10
seed: 7
test_images_txt: stage_1/test_images.txt
train_images_txt: stage_1/train_images.txt
train_masks_txt: stage_1/train_masks.txt
val_images_txt: stage_1/val_images.txt
val_masks_txt: stage_1/val_masks.txt
